property_key_map = {
    "BIRTH_DATE": "birth_date",
    "PATIENT_STATUS": "is_deceased",
    "DEATH_DATE": "death_date",
    "PRIMARY_ONC": "care_provider",
    "PAT_ID": "client_id",
    "PAT_LAST_NAME": "last_name",
    "PAT_FIRST_NAME": "first_name",
    "PAT_MIDDLE_NAME": "middle_name",
    "PAT_TITLE": "prefix",
    "PAT_NAME_SUFFIX": "suffix",
    "SEX": "sex",
    "LANGUAGE": "preferred_language",
    "PATIENT_RACE": "race",
    "ETHNIC_GROUP": "ethnicity",
    "PRIMARY_ONC": "care_provider",
    "EMAIL_ADDRESS": "email",
    "MRN": "mrn",
    "ADD_LINE_1": "street",
    "ADD_LINE_2": "street2",
    "CITY": "city",
    "STATE": "state",
    "ZIP": "postal_code",
    "COUNTRY": "country",
    "CONTACT_PHONE": "phone",
    "DB_UPDATE_DTTM": "extract_date"
}
SEX = {
    'Female': 'Female',
    'Male':	'Male',
    'Unknown': 'Unknown'
}

patient_status ={
    'Alive': False,
    'Deceased': True,
    'N': False,
    'Y': True
}

RACE = {
        "American Indian or Alaskan Native": "American Indian or Alaska Native",
        "Asian": "Asian",
        "Black/African American": "Black or African American",
        "DEACTIVE": "Not Provided",
        "Native Hawaiian": "Native Hawaiian or Other Pacific Islander",
        "Not Asked": "Not Provided",
        "Other Pacific Islander": "Native Hawaiian or Other Pacific Islander",
        "Patient Refused": "Not Provided",
        "Unknown": "Other",
        "White": "White",
        "XXNative Hawaiian/Other Pacific Islander": "Native Hawaiian or Other Pacific Islander",
        "": ""
}

ETHNICITY = {
    "African American": "Non-Hispanic/Non-Latino",
    "Hispanic/Latino Origin": "Hispanic/Latino",
    "Not of Hispanic or Latino Origin": "Non-Hispanic/Non-Latino",
    "Patient Refused": "Unknown",
    "Not Asked": "Unknown",
    "Unknown": "Unknown",
    "": ''
}

LANGUAGES = {
    "Abkhaz": "Abkhaz",
    "Afar": "Afar",
    "Afrikaans": "Afrikaans",
    "Akan": "Akan",
    "Albanian": "Albanian",
    "Amharic": "Amharic",
    "Arabic": "Arabic",
    "Aragonese": "Aragonese",
    "Armenian": "Armenian",
    "Assamese": "Assamese",
    "Avaric": "Avaric",
    "Avestan": "Avestan",
    "Aymara": "Aymara",
    "Azerbaijani": "Azerbaijani",
    "Bambara": "Bambara",
    "Bashkir": "Bashkir",
    "Basque": "Basque",
    "Belarusian": "Belarusian",
    "Bengali": "Bengali",
    "Bihari": "Bihari",
    "Bislama": "Bislama",
    "Bosnian": "Bosnian",
    "Breton": "Breton",
    "Bulgarian": "Bulgarian",
    "Burmese": "Burmese",
    "Cambodian": "Khmer",
    "Catalan (Valencian)": "Catalan",
    "Chamorro": "Chamorro",
    "Chechen": "Chechen",
    "Chichewa (Nyanja)": "Chichewa",
    "Chinese": "Chinese",
    "Chinese-Cantonese": "Chinese",
    "Chinese-Mandarin": "Chinese",
    "Church Slavonic": "Old Church Slavonic",
    "Chuvash": "Chuvash",
    "Cornish": "Cornish",
    "Corsican": "Corsican",
    "Cree": "Cree",
    "Croatian": "Croatian",
    "Czech": "Czech",
    "Danish": "Danish",
    "Divehi (Maldivian)": "Divehi",
    "Dutch": "Dutch",
    "Dzongkha": "Dzongkha",
    "English": "English",
    "Esperanto": "Esperanto",
    "Estonian": "Estonian",
    "Ewe": "Ewe",
    "Faroese": "Faroese",
    "Farsi": "Persian",
    "Farsi (persian)": "Persian",
    "Fijian": "Fijian",
    "Finnish": "Finnish",
    "Flemish": "Dutch",
    "French": "French",
    "Fula": "Fula",
    "Galician": "Galician",
    "Ganda": "Ganda",
    "Georgian": "Georgian",
    "German": "German",
    "Greek": "Greek",
    "Gujarati": "Gujarati",
    "Haitian": "Haitian",
    "Hausa": "Hausa",
    "Hebrew": "Hebrew",
    "Herero": "Herero",
    "Hindi": "Hindi",
    "Hiri Motu": "Hiri Motu",
    "Hungarian": "Hungarian",
    "Icelandic": "Icelandic",
    "Ido": "Ido",
    "Igbo": "Igbo",
    "Indonesian": "Indonesian",
    "Interlingua": "Interlingua",
    "Interlingue": "Interlingue",
    "Inuktitut": "Inuktitut",
    "Inupiaq": "Inupiaq",
    "Irish": "Irish",
    "Italian": "Italian",
    "Japanese": "Japanese",
    "Javanese": "Javanese",
    "Kalaallisut": "Kalaallisut",
    "Kannada": "Kannada",
    "Kanuri": "Kanuri",
    "Kashmiri": "Kashmiri",
    "Kazakh": "Kazakh",
    "Khmer": "Khmer",
    "Kikuyu": "Kikuyu",
    "Kinyarwanda": "Kinyarwanda",
    "Kirundi": "Kirundi",
    "Komi": "Komi",
    "Kongo": "Kongo",
    "Korean": "Korean",
    "Kurdish": "Kurdish",
    "Kwanyama": "Kwanyama",
    "Kyrgyz": "Kyrgyz",
    "Lao": "Lao",
    "Latin": "Latin",
    "Latvian": "Latvian",
    "Limburgish": "Limburgish",
    "Lingala": "Lingala",
    "Lithuanian": "Lithuanian",
    "Luba-Katanga": "Luba-Katanga",
    "Luxembourgish": "Luxembourgish",
    "Macedonian": "Macedonian",
    "Malagasy": "Malagasy",
    "Malay": "Malay",
    "Malayalam": "Malayalam",
    "Maltese": "Maltese",
    "Manx": "Manx",
    "Marathi": "Marathi",
    "Marshallese": "Marshallese",
    "Mongolian": "Mongolian",
    "Nauru": "Nauruan",
    "Navajo": "Navajo",
    "Ndonga": "Ndonga",
    "Nepali": "Nepali",
    "North Ndebele": "Northern Ndebele",
    "Northern Sami": "Northern Sami",
    "Norwegian": "Norwegian",
    "Norwegian Nynorsk": "Norwegian Nynorsk",
    "Nuosu": "Nuosu",
    "Occitan": "Occitan",
    "Ojibwe": "Ojibwe",
    "Oriya": "Oriya",
    "Oromo": "Oromo",
    "Ossetian": "Ossetian",
    "Pakistani": "Urdu",
    "Pashto": "Pashto",
    "Polish": "Polish",
    "Portuguese": "Portuguese",
    "Punjabi": "Eastern Pujabi",
    "Quechua": "Quechua",
    "Romanian": "Romanian",
    "Romansh": "Romansh",
    "Russian": "Russian",
    "Samoan": "Samoan",
    "Sango": "Sango",
    "Sanskrit": "Sanskrit",
    "Sardinian": "Sardinian",
    "Scottish": "Scottish Gaelic",
    "Serbian": "Serbian",
    "Shona": "Shona",
    "Sindhi": "Sindhi",
    "Sinhala": "Sinhalese",
    "Slovak": "Slovak",
    "Slovene": "Slovene",
    "Somali": "Somali",
    "South Azerbaijani": "Azerbaijani",
    "South Ndebele": "Southern Ndebele",
    "Southern Sotho": "Southern Sotho",
    "Spanish": "Spanish",
    "Sundanese": "Sundanese",
    "Swahili": "Swahili",
    "Swati": "Swati",
    "Swedish": "Swedish",
    "Tagalog": "Tagalog",
    "Tahitian": "Tahitian",
    "Tajik": "Tajik",
    "Tamil": "Tamil",
    "Tatar": "Tatar",
    "Telugu": "Telugu",
    "Thai": "Thai",
    "Tibetan": "Tibetan",
    "Tigrinya": "Tigrinya",
    "Tonga": "Tonga",
    "Tsonga": "Tsonga",
    "Tswana": "Tswana",
    "Turkish": "Turkish",
    "Turkmen": "Turkmen",
    "Twi": "Twi",
    "Ukrainian": "Ukrainian",
    "Urdu": "Urdu",
    "Uyghur": "Uyghur",
    "Uzbek": "Uzbek",
    "Venda": "Venda",
    "Vietnamese": "Vietnamese",
    "Walloon": "Walloon",
    "Welsh": "Welsh",
    "Western Frisian": "Western Frisian",
    "Wolof": "Wolof",
    "Xhosa": "Xhosa",
    "Yiddish": "Yiddish",
    "Yoruba": "Yoruba",
    "Zhuang": "Zhuang",
    "Zulu": "Zulu",
    "": ""
}
