{
 "title": "Data Migration",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Data Ingestion", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data Ingestion (Stage)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(Data_Ingestion.syapse_di.Stage.*)"
    }
   ]
  },
  {
   "title": "Data Ingestion (Live)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(Data_Ingestion.syapse_di.Live.*)"
    }
   ]
  },
  { "title": "Data Transfirmation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Syapse Apps (data_transformation_waitingrecord)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(Data_Transformation.syapse_apps.data_transformation_waitingrecord.*)"
    }
   ]
  },
  {
   "title": "Waiting_Record",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "select record_class, count(record_class) from data_transformation_waitingrecord group by record_class"
    }
   ]
  },
  {
   "title": "PDS (ont-record)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(Data_Transformation.syapse_apps_pds.ont_record.*)"
    }
   ]
  },
  {
   "title": "ont_record",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT kb_class, count(kb_class) from ont_record group by kb_class"
    }
   ]
  }
 ]
}