property_key_map = {
    "PROV_ID": "client_id",
    "PROV_NAME": "name",
    "CREDENTIALS": "credential",
    "NPI": "npi",
    "PROV_TYPE": "provider_type",
    "PROCESS_EXTRACT_DTTM": "extract_date"
}

CREDENTIALS = ('', 'BA', 'FNP', 'MBBS', 'BS', 'CTRS', 'RT', 'PERF', 'RD', 'MS CCC-A', 'RN', 'LPN', 'CCRC', 'RPH', 'GN', 'LPC', 'LCSW', 'OD', 'PHD', 'LAT', 'OT', 'DMD', 'RDMS', 'HT', 'PSYD', 'EMT', 'DTR', 'PCA', 'MEDSTUD', 'PT', 'HUC', 'PTA', 'RTT', 'PA', 'RTR', 'PA-C', 'DDS', 'LAC', 'CSA', 'CSW', 'MD', 'MA', 'MT', 'MPT', 'MS', 'CNMT', 'ATR', 'PHARMD',
                   'CNM', 'CRT', 'CGC', 'BSW', 'ND', 'NP', 'RRT', 'AUD', 'SCRIBE', 'CT', 'CDE', 'ARNP', 'CCC-SLP', 'ADV ST', 'LMT', 'ST', 'APNP', 'CMT', 'SN', 'NE2', 'RPSGT', 'NE1', 'DO', 'C-TECH', 'MSW', 'RN MSN', 'DC', 'MSN', 'DPM', 'LE', 'MBA', 'ARRT', 'CNS', 'CRNP', 'SLP', 'MLS', 'AS', 'MLT', 'CNA', 'CRNA', 'LVN', 'LMFT', 'OTA', 'APSW', 'OTR')

provider_type_map = {
    "Abstractor": "Other",
    "Acupuncturist": "Acupuncturist",
    "Advanced Practice Student": "Other",
    "Aesthetician": "Other",
    "Ambulatory Surgical Center": "Other",
    "Anesthesiologist": "Physician",
    "Anesthesiologist Assistant": "Physician assistant",
    "Athletic Trainer Student": "Other",
    "Audiologist": "Audiologist",
    "Audiology Student": "Other",
    "Behavioral Health Facility": "Other",
    "CT Tech": "Other",
    "Call Center": "Other",
    "Card Tech": "Other",
    "Cardiac Rehab Therapist": "Other",
    "Case Manager": "Other",
    "Certified Athletic Trainer": "Other",
    "Certified Diabetes Educator": "Other",
    "Certified Genetic Counselor": "Other",
    "Certified Nurse Specialist": "Registered nurse",
    "Certified Ophthalmic Assistant": "Physician assistant",
    "Certified Ophthalmic Tech": "Other",
    "Certified Optician": "Optician",
    "Chaplain": "Other",
    "Chart Tracking": "Other",
    "Chiropractor": "Chiropractor",
    "Clinical Nurse Specialist": "Registered nurse",
    "Clinical Research Coordinator": "Other",
    "Clinical Support": "Other",
    "Coordinator": "Other",
    "Counselor": "Professional clinical counselor",
    "Dentist": "Dentist",
    "Department Support Staff": "Other",
    "Dietetic Technician": "Other",
    "Durable Medical Equipment": "Other",
    "Echocardiographic Tech": "Other",
    "Exercise Physiologist": "Other",
    "Financial Advisor": "Other",
    "Free Standing Radiology": "Other",
    "Graduate Nurse": "Registered nurse",
    "Health Educator": "Other",
    "Health Information Staff": "Other",
    "Histology Tech": "Other",
    "Home Health": "Other",
    "Hospital": "Other",
    "Hygenist": "Other",
    "I.S. Support Staff": "Other",
    "Intake Specialist": "Other",
    "Interpreter": "Other",
    "Laboratory": "Other",
    "Lead Special Imaging Tech": "Other",
    "Licensed Nurse": "Registered nurse",
    "Licensed Practical Nurse": "Registered nurse",
    "MRI Tech": "Other",
    "Mammography Tech": "Other",
    "Massage Therapist": "Other",
    "Medical Assistant": "Physician Assistant",
    "Medical Lab Tech": "Other",
    "Medical Student": "Other",
    "Medical Technologist": "Other",
    "Medical Transcriptionist": "Other",
    "Midwife": "Midwife",
    "Neuro Tech": "Other",
    "Neurophysiology Technician": "Other",
    "Neurosurgeon": "Physician",
    "Nuclear Medicine Tech": "Other",
    "Nurse Anesthetist": "Other",
    "Nurse Clinician": "Nurse practitioner",
    "Nurse Extern": "Other",
    "Nurse Practitioner": "Nurse practitioner",
    "Nursing Student": "Other",
    "Nutritionist": "Other",
    "Occupational Therapist": "Occupational therapist",
    "Occupational Therapist Assistant": "Physician assistant",
    "Occupational Therapy Student": "Other",
    "Ophthalmic Tech": "Other",
    "Opthalmic Assistant": "Physician assistant",
    "Optometrist": "Optometrist",
    "Oral Surgeon": "Physician",
    "Orthopaedic Tech": "Other",
    "Osteopath": "Other",
    "Outpatient Facility": "Other",
    "Pastoral Care Student": "Other",
    "Pathologist": "Physician",
    "Patient Care Management": "Other",
    "Pediatric Specialist": "Physician",
    "Perfusionist": "Other",
    "Personal Trainer": "Other",
    "Pharmacist": "Pharmacist",
    "Pharmacist Student": "Other",
    "Physical Therapist": "Physical therapist",
    "Physical Therapist Assistant": "Physician assistant",
    "Physical Therapy Assistant Student": "Other",
    "Physical Therapy Student": "Other",
    "Physician": "Physician",
    "Physician Assistant": "Physician assistant",
    "Podiatrist": "Podiatric medical doctor",
    "Psychiatric Specialist": "Psychiatrist",
    "Psychologist": "Psychologist",
    "Psychometrist": "Other",
    "Pulmonary Tech": "Other",
    "Radiation Oncologist": "Physician",
    "Radiologic Tech": "Other",
    "Radiology Student": "Other",
    "Recreational Therapist": "Other",
    "Registered Dietitian": "Other",
    "Registered Health Information Administrator": "Other",
    "Registered Health Information Technician": "Other",
    "Registered Nurse": "Registered nurse",
    "Rehabilitation Aide": "Other",
    "Resident": "Physician",
    "Resource": "Other",
    "Respiratory Care Tech": "Other",
    "Respiratory Therapist": "Respiratory therapist",
    "Scribe": "Other",
    "Skilled Nursing Facility": "Other",
    "Sleep Studies": "Other",
    "Social Worker": "Clinical social worker",
    "Social Worker Student": "Other",
    "Specialist": "Other",
    "Speech Language Pathologist": "Other",
    "Speech Therapist": "Other",
    "Speech Therapy Student": "Other",
    "Speech and Language Pathologist": "Other",
    "Student": "Other",
    "Student Nurse Anesthetist": "Other",
    "Surgical Assistant": "Physician assistant",
    "Surgical Tech": "Other",
    "Technician": "Other",
    "Technologist": "Other",
    "Therapist": "Other",
    "Ultrasound Tech": "Other",
    "Unit Clerk": "Other",
    "Use Default Value": "",
    "Use Original Value": "",
    "Volunteer": "Other",
    "Yoga Instructor": "Other"
}
